export const dummyClientData = [
  {
    id: 1,
    creditorName: 'maestro',
    firstName: 'Malachi',
    lastName: 'Dobrowolny',
    minPaymentPercentage: 5,
    balance: 10138.49,
    isChecked: false,
  },
  {
    id: 2,
    creditorName: 'jcb',
    firstName: 'Tasia',
    lastName: 'Foffano',
    minPaymentPercentage: 4,
    balance: 19080.87,
    isChecked: false,
  },
  {
    id: 3,
    creditorName: 'mastercard',
    firstName: 'Norris',
    lastName: 'Domelow',
    minPaymentPercentage: 5,
    balance: 5154.64,
    isChecked: false,
  },
  {
    id: 4,
    creditorName: 'jcb',
    firstName: 'Cirillo',
    lastName: 'Lamy',
    minPaymentPercentage: 5,
    balance: 13686.03,
    isChecked: false,
  },
  {
    id: 5,
    creditorName: 'jcb',
    firstName: 'Forester',
    lastName: 'Redish',
    minPaymentPercentage: 5,
    balance: 10044.64,
    isChecked: false,
  },
  {
    id: 6,
    creditorName: 'maestro',
    firstName: 'Marijo',
    lastName: 'Dubery',
    minPaymentPercentage: 3,
    balance: 18074.8,
    isChecked: false,
  },
  {
    id: 7,
    creditorName: 'jcb',
    firstName: 'Erina',
    lastName: 'Scotland',
    minPaymentPercentage: 2,
    balance: 12055.58,
    isChecked: false,
  },
  {
    id: 8,
    creditorName: 'diners-club-carte-blanche',
    firstName: 'Alyss',
    lastName: 'Smithson',
    minPaymentPercentage: 5,
    balance: 16380.69,
    isChecked: false,
  },
  {
    id: 9,
    creditorName: 'diners-club-carte-blanche',
    firstName: 'Irwin',
    lastName: 'Kille',
    minPaymentPercentage: 5,
    balance: 18527.75,
    isChecked: false,
  },
  {
    id: 10,
    creditorName: 'jcb',
    firstName: 'Jenn',
    lastName: 'Crownshaw',
    minPaymentPercentage: 2,
    balance: 13228.4,
    isChecked: false,
  },
  {
    id: 11,
    creditorName: 'bankcard',
    firstName: 'Brice',
    lastName: 'Florio',
    minPaymentPercentage: 3,
    balance: 5906.83,
    isChecked: false,
  },
  {
    id: 12,
    creditorName: 'jcb',
    firstName: 'Cheston',
    lastName: 'Albiston',
    minPaymentPercentage: 5,
    balance: 5409.37,
    isChecked: false,
  },
  {
    id: 13,
    creditorName: 'americanexpress',
    firstName: 'Shana',
    lastName: 'Gon',
    minPaymentPercentage: 3,
    balance: 4480.34,
    isChecked: false,
  },
  {
    id: 14,
    creditorName: 'jcb',
    firstName: 'Addison',
    lastName: 'Blackie',
    minPaymentPercentage: 4,
    balance: 11784.26,
    isChecked: false,
  },
  {
    id: 15,
    creditorName: 'visa-electron',
    firstName: 'Maurene',
    lastName: 'Windram',
    minPaymentPercentage: 3,
    balance: 7548.17,
    isChecked: false,
  },
  {
    id: 16,
    creditorName: 'laser',
    firstName: 'Tova',
    lastName: 'Bettley',
    minPaymentPercentage: 3,
    balance: 10225.14,
    isChecked: false,
  },
  {
    id: 17,
    creditorName: 'mastercard',
    firstName: 'Gav',
    lastName: 'Snelgrove',
    minPaymentPercentage: 3,
    balance: 5438.87,
    isChecked: false,
  },
  {
    id: 18,
    creditorName: 'mastercard',
    firstName: 'Zackariah',
    lastName: 'Scarasbrick',
    minPaymentPercentage: 4,
    balance: 5633.57,
    isChecked: false,
  },
  {
    id: 19,
    creditorName: 'jcb',
    firstName: 'Angelina',
    lastName: 'Mew',
    minPaymentPercentage: 4,
    balance: 7455.97,
    isChecked: false,
  },
  {
    id: 20,
    creditorName: 'maestro',
    firstName: 'Chelsae',
    lastName: 'Abrashkov',
    minPaymentPercentage: 2,
    balance: 9679.2,
    isChecked: false,
  },
  {
    id: 21,
    creditorName: 'jcb',
    firstName: 'Carolyne',
    lastName: 'Mattersley',
    minPaymentPercentage: 4,
    balance: 4247.08,
    isChecked: false,
  },
  {
    id: 22,
    creditorName: 'switch',
    firstName: 'Virginie',
    lastName: 'Slym',
    minPaymentPercentage: 5,
    balance: 1373.79,
    isChecked: false,
  },
  {
    id: 23,
    creditorName: 'bankcard',
    firstName: 'Larine',
    lastName: 'Birkbeck',
    minPaymentPercentage: 4,
    balance: 9081.16,
    isChecked: false,
  },
  {
    id: 24,
    creditorName: 'jcb',
    firstName: 'Jeannine',
    lastName: 'Garrison',
    minPaymentPercentage: 4,
    balance: 92.73,
    isChecked: false,
  },
  {
    id: 25,
    creditorName: 'diners-club-enroute',
    firstName: 'Reinaldos',
    lastName: 'Turvey',
    minPaymentPercentage: 2,
    balance: 12185.98,
    isChecked: false,
  },
  {
    id: 26,
    creditorName: 'diners-club-enroute',
    firstName: 'Karolina',
    lastName: 'Garthshore',
    minPaymentPercentage: 3,
    balance: 4726.31,
    isChecked: false,
  },
  {
    id: 27,
    creditorName: 'jcb',
    firstName: 'Nealon',
    lastName: 'Alldre',
    minPaymentPercentage: 2,
    balance: 15601.47,
    isChecked: false,
  },
  {
    id: 28,
    creditorName: 'jcb',
    firstName: 'Drud',
    lastName: 'Buttrum',
    minPaymentPercentage: 5,
    balance: 10515.7,
    isChecked: false,
  },
  {
    id: 29,
    creditorName: 'maestro',
    firstName: 'Annmarie',
    lastName: 'Python',
    minPaymentPercentage: 3,
    balance: 7499.42,
    isChecked: false,
  },
  {
    id: 30,
    creditorName: 'visa-electron',
    firstName: 'Teddy',
    lastName: 'Jordine',
    minPaymentPercentage: 2,
    balance: 19904.92,
    isChecked: false,
  },
  {
    id: 31,
    creditorName: 'jcb',
    firstName: 'Far',
    lastName: 'Brombell',
    minPaymentPercentage: 4,
    balance: 14977.9,
    isChecked: false,
  },
  {
    id: 32,
    creditorName: 'jcb',
    firstName: 'Chic',
    lastName: 'Speddin',
    minPaymentPercentage: 5,
    balance: 16606.36,
    isChecked: false,
  },
  {
    id: 33,
    creditorName: 'americanexpress',
    firstName: 'Raymond',
    lastName: 'Wanklin',
    minPaymentPercentage: 3,
    balance: 3345.4,
    isChecked: false,
  },
  {
    id: 34,
    creditorName: 'switch',
    firstName: 'Ellwood',
    lastName: 'Arrundale',
    minPaymentPercentage: 5,
    balance: 19314.11,
    isChecked: false,
  },
  {
    id: 35,
    creditorName: 'switch',
    firstName: 'Myrilla',
    lastName: 'Stichall',
    minPaymentPercentage: 5,
    balance: 2309.7,
    isChecked: false,
  },
  {
    id: 36,
    creditorName: 'diners-club-enroute',
    firstName: 'Costa',
    lastName: 'Bellhanger',
    minPaymentPercentage: 4,
    balance: 5195.49,
    isChecked: false,
  },
  {
    id: 37,
    creditorName: 'jcb',
    firstName: 'Morse',
    lastName: 'Burghill',
    minPaymentPercentage: 5,
    balance: 5674.57,
    isChecked: false,
  },
  {
    id: 38,
    creditorName: 'bankcard',
    firstName: 'Toma',
    lastName: 'Krikorian',
    minPaymentPercentage: 3,
    balance: 5826.66,
    isChecked: false,
  },
  {
    id: 39,
    creditorName: 'jcb',
    firstName: 'Adore',
    lastName: 'Hanssmann',
    minPaymentPercentage: 4,
    balance: 6774.04,
    isChecked: false,
  },
  {
    id: 40,
    creditorName: 'jcb',
    firstName: 'Fitz',
    lastName: 'Gerritzen',
    minPaymentPercentage: 2,
    balance: 16437.26,
    isChecked: false,
  },
  {
    id: 41,
    creditorName: 'maestro',
    firstName: 'Ashien',
    lastName: 'Ethelston',
    minPaymentPercentage: 2,
    balance: 18827.48,
    isChecked: false,
  },
  {
    id: 42,
    creditorName: 'switch',
    firstName: 'Quintilla',
    lastName: 'Bosquet',
    minPaymentPercentage: 5,
    balance: 5859.34,
    isChecked: false,
  },
  {
    id: 43,
    creditorName: 'jcb',
    firstName: 'Nettle',
    lastName: 'Bernade',
    minPaymentPercentage: 5,
    balance: 11459.83,
    isChecked: false,
  },
  {
    id: 44,
    creditorName: 'jcb',
    firstName: 'Elston',
    lastName: 'Nance',
    minPaymentPercentage: 2,
    balance: 10089.74,
    isChecked: false,
  },
  {
    id: 45,
    creditorName: 'jcb',
    firstName: 'Raymund',
    lastName: 'Vondra',
    minPaymentPercentage: 2,
    balance: 18211.03,
    isChecked: false,
  },
  {
    id: 46,
    creditorName: 'jcb',
    firstName: 'Harold',
    lastName: 'Parnell',
    minPaymentPercentage: 5,
    balance: 14394.92,
    isChecked: false,
  },
  {
    id: 47,
    creditorName: 'diners-club-carte-blanche',
    firstName: 'Nikolaos',
    lastName: 'Crosbie',
    minPaymentPercentage: 4,
    balance: 13061.12,
    isChecked: false,
  },
  {
    id: 48,
    creditorName: 'jcb',
    firstName: 'Ambrosi',
    lastName: 'Danielsen',
    minPaymentPercentage: 4,
    balance: 14463.43,
    isChecked: false,
  },
  {
    id: 49,
    creditorName: 'jcb',
    firstName: 'Darcey',
    lastName: 'Pentin',
    minPaymentPercentage: 3,
    balance: 9409.32,
    isChecked: false,
  },
  {
    id: 50,
    creditorName: 'bankcard',
    firstName: 'Hatti',
    lastName: 'Gerriessen',
    minPaymentPercentage: 2,
    balance: 19770.23,
    isChecked: false,
  },
  {
    id: 51,
    creditorName: 'jcb',
    firstName: 'Dougie',
    lastName: 'Swannell',
    minPaymentPercentage: 3,
    balance: 820.39,
    isChecked: false,
  },
  {
    id: 52,
    creditorName: 'bankcard',
    firstName: 'Dorie',
    lastName: 'Trenam',
    minPaymentPercentage: 5,
    balance: 19287.07,
    isChecked: false,
  },
  {
    id: 53,
    creditorName: 'mastercard',
    firstName: 'Lionello',
    lastName: 'Lawdham',
    minPaymentPercentage: 5,
    balance: 14441.01,
    isChecked: false,
  },
  {
    id: 54,
    creditorName: 'solo',
    firstName: 'Johan',
    lastName: 'Maccrea',
    minPaymentPercentage: 4,
    balance: 17316.17,
    isChecked: false,
  },
  {
    id: 55,
    creditorName: 'jcb',
    firstName: 'Foss',
    lastName: 'Hiskey',
    minPaymentPercentage: 4,
    balance: 11830.81,
    isChecked: false,
  },
  {
    id: 56,
    creditorName: 'bankcard',
    firstName: 'Jo ann',
    lastName: 'Wiper',
    minPaymentPercentage: 4,
    balance: 5861.57,
    isChecked: false,
  },
  {
    id: 57,
    creditorName: 'switch',
    firstName: 'Lodovico',
    lastName: 'Cruise',
    minPaymentPercentage: 2,
    balance: 4600.95,
    isChecked: false,
  },
  {
    id: 58,
    creditorName: 'maestro',
    firstName: 'Morganica',
    lastName: 'Ellph',
    minPaymentPercentage: 2,
    balance: 14387.39,
    isChecked: false,
  },
  {
    id: 59,
    creditorName: 'jcb',
    firstName: 'Gennifer',
    lastName: 'Tewkesberry',
    minPaymentPercentage: 3,
    balance: 13685.3,
    isChecked: false,
  },
  {
    id: 60,
    creditorName: 'jcb',
    firstName: 'Lianne',
    lastName: 'Stoggles',
    minPaymentPercentage: 5,
    balance: 8909.13,
    isChecked: false,
  },
  {
    id: 61,
    creditorName: 'americanexpress',
    firstName: 'Marquita',
    lastName: 'Quelch',
    minPaymentPercentage: 5,
    balance: 1944.82,
    isChecked: false,
  },
  {
    id: 62,
    creditorName: 'diners-club-enroute',
    firstName: 'Lizabeth',
    lastName: 'Bricknall',
    minPaymentPercentage: 3,
    balance: 19176.36,
    isChecked: false,
  },
  {
    id: 63,
    creditorName: 'laser',
    firstName: 'Garald',
    lastName: 'Josephov',
    minPaymentPercentage: 2,
    balance: 17220.36,
    isChecked: false,
  },
  {
    id: 64,
    creditorName: 'jcb',
    firstName: 'Lia',
    lastName: 'Broxholme',
    minPaymentPercentage: 3,
    balance: 16478.56,
    isChecked: false,
  },
  {
    id: 65,
    creditorName: 'diners-club-international',
    firstName: 'Maribelle',
    lastName: 'Jiggen',
    minPaymentPercentage: 2,
    balance: 12222.32,
    isChecked: false,
  },
  {
    id: 66,
    creditorName: 'china-unionpay',
    firstName: 'Shannah',
    lastName: 'Scales',
    minPaymentPercentage: 4,
    balance: 10098.64,
    isChecked: false,
  },
  {
    id: 67,
    creditorName: 'bankcard',
    firstName: 'Cordy',
    lastName: 'McIlenna',
    minPaymentPercentage: 5,
    balance: 18186.56,
    isChecked: false,
  },
  {
    id: 68,
    creditorName: 'visa',
    firstName: 'Karalee',
    lastName: 'Brazear',
    minPaymentPercentage: 4,
    balance: 8292.61,
    isChecked: false,
  },
  {
    id: 69,
    creditorName: 'switch',
    firstName: 'Ambur',
    lastName: 'Kaaskooper',
    minPaymentPercentage: 5,
    balance: 6186.28,
    isChecked: false,
  },
  {
    id: 70,
    creditorName: 'laser',
    firstName: 'Sarette',
    lastName: 'Macvey',
    minPaymentPercentage: 3,
    balance: 16933.66,
    isChecked: false,
  },
  {
    id: 71,
    creditorName: 'visa-electron',
    firstName: 'Hesther',
    lastName: 'Havelin',
    minPaymentPercentage: 4,
    balance: 3012.55,
    isChecked: false,
  },
  {
    id: 72,
    creditorName: 'jcb',
    firstName: 'Marsha',
    lastName: 'Walczak',
    minPaymentPercentage: 2,
    balance: 12636.6,
    isChecked: false,
  },
  {
    id: 73,
    creditorName: 'visa-electron',
    firstName: 'Valenka',
    lastName: 'Reasun',
    minPaymentPercentage: 5,
    balance: 16893.52,
    isChecked: false,
  },
  {
    id: 74,
    creditorName: 'diners-club-enroute',
    firstName: 'Kelsi',
    lastName: 'Cana',
    minPaymentPercentage: 4,
    balance: 7565.03,
    isChecked: false,
  },
  {
    id: 75,
    creditorName: 'jcb',
    firstName: 'Ford',
    lastName: 'McCritichie',
    minPaymentPercentage: 5,
    balance: 1468.82,
    isChecked: false,
  },
  {
    id: 76,
    creditorName: 'maestro',
    firstName: 'Aloise',
    lastName: 'Baselli',
    minPaymentPercentage: 2,
    balance: 4685.7,
    isChecked: false,
  },
  {
    id: 77,
    creditorName: 'diners-club-carte-blanche',
    firstName: 'Giraud',
    lastName: 'Blakeley',
    minPaymentPercentage: 2,
    balance: 12156.75,
    isChecked: false,
  },
  {
    id: 78,
    creditorName: 'visa-electron',
    firstName: 'Isadore',
    lastName: 'Itter',
    minPaymentPercentage: 3,
    balance: 7315.52,
    isChecked: false,
  },
  {
    id: 79,
    creditorName: 'solo',
    firstName: 'Kylie',
    lastName: 'Welling',
    minPaymentPercentage: 5,
    balance: 11653.47,
    isChecked: false,
  },
  {
    id: 80,
    creditorName: 'jcb',
    firstName: 'Zaneta',
    lastName: 'Wagge',
    minPaymentPercentage: 2,
    balance: 2653.96,
    isChecked: false,
  },
  {
    id: 81,
    creditorName: 'mastercard',
    firstName: 'Isa',
    lastName: 'Popping',
    minPaymentPercentage: 3,
    balance: 17583.2,
    isChecked: false,
  },
  {
    id: 82,
    creditorName: 'jcb',
    firstName: 'Joelle',
    lastName: 'Humfrey',
    minPaymentPercentage: 2,
    balance: 4555.18,
    isChecked: false,
  },
  {
    id: 83,
    creditorName: 'jcb',
    firstName: 'Buffy',
    lastName: 'Minter',
    minPaymentPercentage: 5,
    balance: 12205.65,
    isChecked: false,
  },
  {
    id: 84,
    creditorName: 'jcb',
    firstName: 'Lincoln',
    lastName: 'Strase',
    minPaymentPercentage: 4,
    balance: 13464.26,
    isChecked: false,
  },
  {
    id: 85,
    creditorName: 'jcb',
    firstName: 'Olin',
    lastName: 'Handman',
    minPaymentPercentage: 3,
    balance: 7670.78,
    isChecked: false,
  },
  {
    id: 86,
    creditorName: 'jcb',
    firstName: 'Chancey',
    lastName: 'Gerrans',
    minPaymentPercentage: 4,
    balance: 459.14,
    isChecked: false,
  },
  {
    id: 87,
    creditorName: 'jcb',
    firstName: 'Cirillo',
    lastName: 'Haime',
    minPaymentPercentage: 5,
    balance: 18312.84,
    isChecked: false,
  },
  {
    id: 88,
    creditorName: 'jcb',
    firstName: 'Paolo',
    lastName: 'Twizell',
    minPaymentPercentage: 4,
    balance: 10069.97,
    isChecked: false,
  },
  {
    id: 89,
    creditorName: 'switch',
    firstName: 'Brendan',
    lastName: 'Widdup',
    minPaymentPercentage: 2,
    balance: 15740.02,
    isChecked: false,
  },
  {
    id: 90,
    creditorName: 'jcb',
    firstName: 'Casie',
    lastName: 'Newham',
    minPaymentPercentage: 2,
    balance: 13810.86,
    isChecked: false,
  },
  {
    id: 91,
    creditorName: 'maestro',
    firstName: 'Akim',
    lastName: 'Raitie',
    minPaymentPercentage: 3,
    balance: 12039.07,
    isChecked: false,
  },
  {
    id: 92,
    creditorName: 'mastercard',
    firstName: 'Jillene',
    lastName: 'Jurgenson',
    minPaymentPercentage: 4,
    balance: 16149.43,
    isChecked: false,
  },
  {
    id: 93,
    creditorName: 'mastercard',
    firstName: 'Betta',
    lastName: 'Brunone',
    minPaymentPercentage: 5,
    balance: 15499.96,
    isChecked: false,
  },
  {
    id: 94,
    creditorName: 'visa',
    firstName: 'Jordan',
    lastName: 'Geater',
    minPaymentPercentage: 3,
    balance: 5031.76,
    isChecked: false,
  },
  {
    id: 95,
    creditorName: 'jcb',
    firstName: 'Shannon',
    lastName: 'Camlin',
    minPaymentPercentage: 4,
    balance: 9223.62,
    isChecked: false,
  },
  {
    id: 96,
    creditorName: 'jcb',
    firstName: 'Devan',
    lastName: 'Jaray',
    minPaymentPercentage: 5,
    balance: 16869.09,
    isChecked: false,
  },
  {
    id: 97,
    creditorName: 'jcb',
    firstName: 'Melina',
    lastName: 'Nassi',
    minPaymentPercentage: 4,
    balance: 5172.73,
    isChecked: false,
  },
  {
    id: 98,
    creditorName: 'americanexpress',
    firstName: 'Hazel',
    lastName: 'Varns',
    minPaymentPercentage: 5,
    balance: 6667.63,
    isChecked: false,
  },
  {
    id: 99,
    creditorName: 'jcb',
    firstName: 'Teodor',
    lastName: 'Franseco',
    minPaymentPercentage: 3,
    balance: 13983.36,
    isChecked: false,
  },
  {
    id: 100,
    creditorName: 'jcb',
    firstName: 'Thor',
    lastName: 'Sprey',
    minPaymentPercentage: 5,
    balance: 4562.4,
    isChecked: false,
  },
];